const express = require("express");
const crypto = require("crypto");
const { db, DURATIONS, balance, config, saveConfig, allowanceRemaining, insertLedger, checkAndChargeGate } = require("../economy");

function gate(feature) { return async (req, res, next) => { const result = await checkAndChargeGate(feature, req.get("x-vectr-session") || "", req.get("x-vectr-device") || "anonymous"); if (result.allowed) return next(); return res.status(402).json({ error: "gate.denied", feature, balance: result.newBalance, cost: result.cost }); }; }
function createPointsRoutes() {
  const router = express.Router();
  router.get("/points/balance", async (_req, res, next) => { try { const firstUseFreeRemaining = await allowanceRemaining(); res.json({ balance: balance(), firstUseFreeRemaining, freeAllowanceRemainingToday: firstUseFreeRemaining }); } catch (error) { next(error); } });
  router.get("/points/config", async (_req, res, next) => { try { res.json(await config()); } catch (error) { next(error); } });
  router.post("/points/config", async (req, res, next) => { try { res.json(await saveConfig(req.body || {})); } catch (error) { res.status(400); next(error); } });
  router.post("/points/reset", (_req, res) => { const current = balance(); if (current) insertLedger(-current, "manual_reset"); res.json({ balance: balance() }); });
  router.post("/voyages/start", async (req, res, next) => { try { const tier = req.body?.durationTier; const settings = await config(); let duration = DURATIONS[tier]; let reward = settings.voyageRewards[tier]; if (tier === "custom") { duration = Number(req.body?.customDurationSeconds); if (!Number.isInteger(duration) || duration <= settings.customMinimumDurationSeconds) return res.status(400).json({ error: "Custom voyages must be longer than 1.5 hours" }); reward = Math.round(3000 + settings.customMarginalRatePerMinute * ((duration - settings.customMinimumDurationSeconds) / 60)); } if (!Number.isInteger(duration) || !Number.isFinite(Number(reward))) return res.status(400).json({ error: "Invalid duration tier." }); const id = crypto.randomUUID(); const now = new Date(); db.prepare("INSERT INTO voyages (id, duration_tier, duration_seconds, start_time, status, planned_reward) VALUES (?, ?, ?, ?, 'in_progress', ?)").run(id, tier, duration, now.toISOString(), reward); res.status(201).json({ id, plannedEndTime: new Date(now.getTime() + duration * 1000).toISOString(), durationSeconds: duration, plannedReward: reward }); } catch (error) { next(error); } });
  router.post("/voyages/:id/complete", async (req, res, next) => { try { const voyage = db.prepare("SELECT * FROM voyages WHERE id = ?").get(req.params.id); if (!voyage) return res.status(404).json({ error: "Voyage not found." }); if (voyage.status !== "in_progress") return res.status(409).json({ error: "Voyage is no longer in progress." }); const elapsed = Date.now() - Date.parse(voyage.start_time); if (elapsed < voyage.duration_seconds * 1000) return res.status(409).json({ error: "This voyage has not reached its destination yet." }); const reward = Number(voyage.planned_reward); if (!Number.isFinite(reward)) return res.status(409).json({ error: "Voyage reward is unavailable." }); db.prepare("UPDATE voyages SET status = 'completed', end_time = ?, berries_awarded = ? WHERE id = ?").run(new Date().toISOString(), reward, voyage.id); insertLedger(reward, "voyage_completed", voyage.duration_tier); res.json({ berriesAwarded: reward, balance: balance() }); } catch (error) { next(error); } });
  router.post("/voyages/:id/abandon", async (req, res, next) => { try { const voyage = db.prepare("SELECT * FROM voyages WHERE id = ?").get(req.params.id); if (!voyage) return res.status(404).json({ error: "Voyage not found." }); if (voyage.status !== "in_progress") return res.status(409).json({ error: "Voyage is no longer in progress." }); const settings = await config(); const penalty = Math.min(balance(), Math.floor(Number(voyage.planned_reward) * Number(settings.abandonPenaltyPercent) / 100)); db.prepare("UPDATE voyages SET status = 'abandoned', end_time = ?, berries_awarded = ? WHERE id = ?").run(new Date().toISOString(), -penalty, voyage.id); if (penalty) insertLedger(-penalty, "abandon_ship", voyage.duration_tier); res.json({ berriesDeducted: penalty, balance: balance() }); } catch (error) { next(error); } });
  router.get("/voyages/history", (_req, res) => res.json(db.prepare("SELECT * FROM voyages ORDER BY start_time DESC LIMIT 100").all()));
  return router;
}
module.exports = { createPointsRoutes, gate };
